orbs:
  node: circleci/node@2.0.2

version: 2.1

workflows:
  node-test:
    jobs:
      - node/test

      ##The React. js framework is an open-source JavaScript framework and library developed by Facebook. It's used for building interactive user interfaces and web applications quickly and efficiently with significantly less code than you would with vanilla JavaScript.Jun 27, 2022
